### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alexbegt** [TeamBW/NetherEnhancements#2]
Do you use eclipse? If so, you should be using formatters and i'm going to be doing a new pr to show you something that's helpful.

**Comment by Chaka15205** [comment]
I'm Using IntelliJ

**Comment by alexbegt** [comment]
Oh, i like eclipse because i can make it format the class when i save it, that's why all the classes got broke lol

**Comment by Chaka15205** [comment]
lol, So what did you want to pr? Also, Should I get on IRC?  I'm on teamspeak right now.

**Comment by alexbegt** [comment]
Yes get on irc please.
